// Run without dependencies or generated artifacts: node --test tests/compound.test.cjs
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const quietConsole = { info() {}, log() {}, warn() {}, error() {} };

// Exercise the actual browser entry point, validation, formatting and results.
// All DOM and statistics effects stay in memory; no network or storage is used.
function harness(overrides = {}) {
    const elements = new Map();
    const listeners = new Map();
    const alerts = [];
    const recorded = [];
    const values = new Map();
    let focused = null;
    const document = {
        addEventListener(type, callback) { listeners.set(type, callback); },
        getElementById(id) {
            if (!elements.has(id)) {
                const classes = new Set();
                elements.set(id, {
                    value: '', innerHTML: '', style: {},
                    focus() { focused = id; },
                    classList: {
                        add(value) { classes.add(value); },
                        remove(value) { classes.delete(value); },
                        contains(value) { return classes.has(value); }
                    }
                });
            }
            return elements.get(id);
        }
    };
    const context = {
        document, console: quietConsole,
        alert(message) { alerts.push(message); },
        ToolXoneStatisticsEvents: {
            recordCalculation(id) { recorded.push(id); }
        }
    };
    context.window = context;
    vm.createContext(context);
    vm.runInContext(read('js/number-engine.js'), context);
    vm.runInContext(read('js/compound.js'), context);
    for (const name of ['createCompoundMoneyResult', 'createCompoundPercentResult']) {
        const original = context[name];
        context[name] = (label, value) => {
            values.set(label, value);
            return original(label, value);
        };
    }
    const inputs = {
        principal: 1000, monthly: 100, rate: 12, years: 1, frequency: 12,
        ...overrides
    };
    for (const [id, value] of Object.entries(inputs)) {
        document.getElementById(id).value = String(value);
    }
    return {
        context, document, listeners, alerts, recorded, values,
        get focused() { return focused; },
        run() { context.runCompoundCalculator(); }
    };
}

function near(actual, expected, tolerance = 1e-8) {
    assert.ok(Number.isFinite(actual), 'Expected a finite number, received ' + actual);
    assert.ok(Math.abs(actual - expected) <= tolerance,
        'Expected ' + expected + ', received ' + actual);
}

// Independent cash-flow reference values from the approved design, not values
// generated by a copy of the implementation under test. All rates are percent.
const references = [
    ['A yearly, principal only', 1000, 0, 12, 1, 1, 1120, 1000],
    ['B quarterly, principal only', 1000, 0, 12, 4, 1, 1125.50881, 1000],
    ['C monthly, principal only', 1000, 0, 12, 12, 1, 1126.8250301320, 1000],
    ['D daily, principal only', 1000, 0, 12, 365, 1, 1127.4746156384, 1000],
    ['E yearly with deposits', 1000, 100, 12, 1, 1, 2396.6497908353, 2200],
    ['F quarterly with deposits', 1000, 100, 12, 4, 1, 2405.6162313318, 2200],
    ['G monthly with deposits', 1000, 100, 12, 12, 1, 2407.7578344649, 2200],
    ['H daily with deposits', 1000, 100, 12, 365, 1, 2408.8146597587, 2200],
    ['I partial annual period, principal only', 1000, 0, 12, 1, 1.5, 1185.2965873569, 1000],
    ['J partial annual period with deposits', 1000, 100, 12, 1, 1.5, 3156.6203331214, 2800],
    ['K two months of quarterly growth', 1000, 100, 12, 4, 1 / 6, 1222.8816049075, 1200],
    ['L first deposit earns one month, no ending deposit', 1000, 100, 12, 12, 1 / 12, 1111, 1100],
    ['M zero rate with deposits', 1000, 100, 0, 365, 1.5, 2800, 2800],
    ['N zero rate without deposits', 1000, 0, 0, 1, 1.5, 1000, 1000],
    ['O decimal amounts and rate', 1234.56, 78.90, 4.5, 4, 1.25, 2525.0811201347, 2418.06],
    ['P very small positive rate', 1000, 100, 0.00000001, 12, 1, 2200.0000001650, 2200]
];

for (const [name, principal, monthly, rate, frequency, years, future, contributions] of references) {
    test(name + ': expected FV ' + future.toFixed(2), () => {
        const h = harness({ principal, monthly, rate, frequency, years });
        h.run();
        assert.deepEqual(h.alerts, []);
        near(h.values.get('Future Value'), future);
        near(h.values.get('Total Contributions'), contributions);
        near(h.values.get('Interest Earned'), future - contributions);
        near(h.values.get('Growth'), 100 * (future - contributions) / contributions);
        near(h.values.get('Total Contributions') + h.values.get('Interest Earned'),
            h.values.get('Future Value'));
        const html = h.document.getElementById('compoundResult').innerHTML;
        const formatted = new Intl.NumberFormat('en-US', {
            minimumFractionDigits: 2, maximumFractionDigits: 2
        });
        for (const value of [future, contributions, future - contributions]) {
            assert.ok(html.includes(formatted.format(value)));
        }
        assert.ok(html.includes((100 * (future - contributions) / contributions).toFixed(2) + '%'));
        assert.deepEqual(h.recorded, ['compound-interest-calculator']);
        near(parseFloat(h.document.getElementById('investmentBar').style.width),
            100 * contributions / future);
        near(parseFloat(h.document.getElementById('interestBar').style.width),
            100 * (future - contributions) / future);
    });
}

for (const frequency of [1, 4, 12, 365]) {
    test('zero interest is exact with decimal deposits, frequency ' + frequency, () => {
        const h = harness({ principal: 1234.56, monthly: 78.9, years: 1.25, rate: 0, frequency });
        h.run();
        assert.deepEqual(h.alerts, []);
        assert.equal(h.values.get('Future Value'), h.values.get('Total Contributions'));
        assert.equal(h.values.get('Interest Earned'), 0);
        assert.equal(h.values.get('Growth'), 0);
    });
    test('blank deposit equals zero, frequency ' + frequency, () => {
        const blank = harness({ monthly: '', frequency });
        const zero = harness({ monthly: 0, frequency });
        blank.run();
        zero.run();
        assert.deepEqual(blank.alerts, []);
        assert.deepEqual([...blank.values], [...zero.values]);
    });
}

for (const [years, frequency, future, contributions] of [
    ['0.0833333333', 12, 1111, 1100],
    ['0.1666666667', 4, 1222.8816049075, 1200],
    [(12 + 5e-9) / 12, 1, 2396.6497908353, 2200],
    [(12 - 5e-9) / 12, 1, 2396.6497908353, 2200]
]) {
    test('normalize an extremely close whole-month duration: ' + years, () => {
        const h = harness({ years, frequency });
        h.run();
        assert.deepEqual(h.alerts, []);
        near(h.values.get('Future Value'), future);
        assert.equal(h.values.get('Total Contributions'), contributions);
    });
}

const invalid = [
    ['genuine fractional months', { years: 1.1 }, 'years'],
    ['outside month tolerance above', { years: (12 + 2e-8) / 12 }, 'years'],
    ['outside month tolerance below', { years: (12 - 2e-8) / 12 }, 'years'],
    ['zero months after normalization', { years: 1e-12 }, 'years'],
    ['zero duration', { years: 0 }, 'years'],
    ['negative duration', { years: -1 }, 'years'],
    ['over maximum duration', { years: 100.1 }, 'years'],
    ['blank duration', { years: '' }, 'years'],
    ['nonfinite duration', { years: Infinity }, 'years'],
    ['zero principal', { principal: 0 }, 'principal'],
    ['negative principal', { principal: -1 }, 'principal'],
    ['over maximum principal', { principal: 1e15 + 1 }, 'principal'],
    ['nonfinite principal', { principal: Infinity }, 'principal'],
    ['negative contribution', { monthly: -1 }, 'monthly'],
    ['over maximum contribution', { monthly: 1e12 + 1 }, 'monthly'],
    ['nonfinite contribution', { monthly: Infinity }, 'monthly'],
    ['negative rate', { rate: -1 }, 'rate'],
    ['over maximum rate', { rate: 1001 }, 'rate'],
    ['nonfinite rate', { rate: Infinity }, 'rate'],
    ['semiannual is unsupported', { frequency: 2 }, 'frequency'],
    ['zero frequency', { frequency: 0 }, 'frequency'],
    ['invalid frequency', { frequency: 'invalid' }, 'frequency']
];
for (const [name, inputs, focused] of invalid) {
    test('reject ' + name, () => {
        const h = harness(inputs);
        h.run();
        assert.equal(h.alerts.length, 1);
        assert.equal(h.focused, focused);
        assert.equal(h.values.size, 0);
        assert.equal(h.document.getElementById('compoundResult').innerHTML, '');
        assert.deepEqual(h.recorded, []);
    });
}

test('overflow is rejected without publishing a nonfinite result or statistics', () => {
    const h = harness({ rate: 1000, years: 100, frequency: 365 });
    h.run();
    assert.equal(h.alerts.length, 1);
    assert.match(h.alerts[0], /invalid result/);
    assert.equal(h.values.size, 0);
    assert.equal(h.document.getElementById('compoundResult').innerHTML, '');
    assert.deepEqual(h.recorded, []);
});

test('maximum duration remains accepted when the result is finite', () => {
    const h = harness({ years: 100, rate: 0 });
    h.run();
    assert.deepEqual(h.alerts, []);
    assert.equal(h.values.get('Future Value'), 121000);
});

test('Enter calculates once and reset preserves the existing Monthly reset default', () => {
    const h = harness();
    let prevented = false;
    h.listeners.get('keydown')({
        key: 'Enter', target: { matches: () => true },
        preventDefault() { prevented = true; }
    });
    assert.equal(prevented, true);
    near(h.values.get('Future Value'), 2407.7578344649);
    assert.deepEqual(h.recorded, ['compound-interest-calculator']);
    h.context.resetCompound();
    for (const id of ['principal', 'monthly', 'rate', 'years']) {
        assert.equal(h.document.getElementById(id).value, '');
    }
    assert.equal(h.document.getElementById('frequency').value, '12');
    assert.equal(h.document.getElementById('compoundResult').classList.contains('active'), false);
    assert.equal(h.document.getElementById('growthBars').style.display, 'none');
    assert.equal(h.document.getElementById('investmentBar').style.width, '0%');
    assert.equal(h.document.getElementById('interestBar').style.width, '0%');
});

test('existing UI keeps only its four frequencies and the Yearly first option', () => {
    const html = read('compound-interest-calculator.html');
    const inline = [...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)]
        .find(match => match[1].includes('const compoundCalculator ='));
    assert.ok(inline);
    let config;
    vm.runInNewContext(inline[1], {
        createFinanceCalculator(value) { config = value; },
        ToolXoneHeroRenderer: { render() {} }
    });
    assert.deepEqual(Array.from(config.fields, field => field.id),
        ['principal', 'monthly', 'rate', 'years', 'frequency']);
    assert.equal(config.fields.find(field => field.id === 'years').label, 'Investment Period (Years)');
    assert.deepEqual(Array.from(config.fields.find(field => field.id === 'frequency').options,
        option => option.value), ['1', '4', '12', '365']);
});

test('calculation assumptions in compound FAQ and schema agree', () => {
    let faq;
    let schema;
    const registry = {
        register(type, id, value) {
            if (type === 'faq' && id === 'compound-interest-calculator') faq = value;
        }
    };
    const context = {
        console: quietConsole, ToolXoneContentRegistry: registry,
        ToolXoneSchemaRegistry: { register(id, value) { schema = value; } }
    };
    context.window = context;
    vm.createContext(context);
    vm.runInContext(read('js/content/content-data-finance.js'), context);
    vm.runInContext(read('js/seo/schemas/compound-interest-calculator-schema.js'), context);
    const questions = [
        'Does adding monthly contributions affect compound growth?',
        'Does compounding frequency affect the result?',
        'Is the annual interest rate an effective annual yield or APY?',
        'How are partial compounding periods handled?',
        'Can I enter a duration that includes part of a year?',
        'How is daily compounding approximated?',
        'What does the growth percentage mean?',
        'What happens at zero interest?'
    ];
    for (const question of questions) {
        const visible = faq.find(item => item.question === question);
        const structured = schema.schema.faq.find(item => item.question === question);
        assert.ok(visible && structured, question);
        assert.equal(visible.answer, structured.answer, question);
    }
});
